# Generated by Django 4.0.5 on 2022-06-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='quantity',
            field=models.IntegerField(max_length=50),
        ),
    ]
